### ISSUE TITLE
Show Custom Error Messages

### ISSUE THREAD

**Issue by dogansoft** [Sajidur78/CredNet#4]
Dear Friends;

I Need Show Custom Error Messages

Simple
1) Incorrect User Name or Password
2) Username and Password Cannot be Empty
3) and etc..

Please Can you help me urgently?

thanks
best regards

**Comment by Sajidur78** [comment]
There was an error in the library that stopped status text from displaying, fixed in c6f4cdf64c0ced2feeb71086c316a9664f62210c. Check [personalized sample](https://github.com/Sajidur78/CredNet/blob/master/Samples/CredNet.Sample/PersonalizedSampleCredential.cs#L51) to see how error messages should be displayed. I'll close this issue once the nuget package is published.

**Comment by Sajidur78** [comment]
[Package](https://www.nuget.org/packages/CredNet/1.1.3.2) has been published. Closing.
